### ISSUE TITLE
allowing for package install in rstudio

### ISSUE THREAD

**Issue by Analect** [lsetiawan/jnrstud-minimal#1]
@lsetiawan ... I was experimenting with your setup that mixes jupyterlab with rstudio.  Thanks.
However, given that you are dropped in as user jovyan (ie. non root) into rstudio ... there's a restriction in adding new packages from within the running server ... is there any way around this, or do I have to install packages as root as part of the docker image build process?

Also, have you tried installing an R kernel in the jupyter/jupyterlab set-up?  Thanks.

**Comment by lsetiawan** [comment]
@Analect Thank you for following up about this setup. 

>  is there any way around this, or do I have to install packages as root as part of the docker image build process?

I have updated the Dockerfile so that you can install R packages in RStudio and also use R Shiny. 

>  Also, have you tried installing an R kernel in the jupyter/jupyterlab set-up?  Thanks.

You can install [`r-irkernel`](https://anaconda.org/r/r-irkernel) so that you can run R within Jupyter Notebooks, but there will be a disconnect within the RStudio R environment and the Jupyter notebook R environment. My current setup right now uses `nbrsessionproxy` and `nbserverproxy` to proxy RStudio that's running in the background, so the environment between Jupyter Notebook and RStudio is actually separated.

If you like to be able to run R just within Jupyter Notebook using R kernel, you can take a look at the setup [here](https://github.com/BiG-CZ/wshp2017_tutorial_content/blob/master/Dockerfile)

Please let me know if you have further questions. Thanks!

**Comment by Analect** [comment]
@lsetiawan .
Thanks for the info.  That's much appreciated.  I'll close this out for now.
